### ISSUE TITLE
Add a metric to rate limiter for “skipped token” due to token bucket being full

### ISSUE THREAD

**Issue by thinkingfish** [iopsystems/rpc-perf#199]
When server falls behind rate limit, requests are not enqueued in a timely manner. Recording the number of requests skipped with a metric (counter?) will provide a quick view of the number of requests that would have been sent had the server kept up. This metric can also be used to implement smart stop criterion (e.g. if X% of requests were skipped for time period Y then stop the experiment).

**Comment by brayniac** [comment]
This was completed in #201 and included in release 5.7.0
