### ISSUE TITLE
(Question) How it's related to the Twitter repository?

### ISSUE THREAD

**Issue by hardBSDk** [iopsystems/rpc-perf#210]
Is this a continuation?

https://github.com/twitter/rpc-perf

**Comment by brayniac** [comment]
That’s correct. After losing access to the original repo, we decided to continue the project here. Since then, there was also a clean rewrite of the entire code base. So you may notice some significant differences compared to the original repo. 

Let me know if you have any other questions.

**Comment by hardBSDk** [comment]
@brayniac Thanks! my question is satisfied.
